export const queryKeys = {
  me: ['me'] as const,
  sessionsToday: ['sessions', 'today'] as const,
  sessionsRecent: ['sessions', 'recent'] as const,
  sessionDetail: (sessionId: string) => ['sessions', sessionId] as const,
  sessionNote: (sessionId: string) => ['sessions', sessionId, 'note'] as const,
  archiveMe: ['archive', 'me'] as const,
  highlightDetail: (highlightId: string) => ['highlight', highlightId] as const,
  myHighlights: ['highlights', 'me'] as const,
  blogList: ['blog', 'list'] as const,
  blogDetail: (postId: string) => ['blog', postId] as const,
  quizJob: (jobId: string) => ['quiz', 'job', jobId] as const,
  quizDetail: (quizId: string) => ['quiz', 'detail', quizId] as const,
  quizAttempt: (quizId: string, attemptId: string) => ['quiz', 'attempt', quizId, attemptId] as const,
  highlightSessionQuizResult: (sessionId: string) => ['highlight', 'quiz-result', sessionId] as const,
  highlight: {
    list: ['highlight', 'list'] as const,
  },
  feedPosts: ['feed', 'posts'] as const,
  feedComments: (postId: string) => ['feed', 'comments', postId] as const,
} as const;
