"""Drop deprecated, add interest and log

Revision ID: 938501b9a3f2
Revises: 20260329_0002
Create Date: 2026-04-07 22:39:41.603745
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '938501b9a3f2'
down_revision = '20260329_0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interests',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('profile_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('started_at', sa.Date(), nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('interest_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('tag', sa.Enum('TASTING_NOTE', 'READING', 'VISIT', 'OBSERVATION', 'OTHER', name='log_tag_enum', native_enum=False), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_highlights_profile_id_published_at'), table_name='highlights')
    op.drop_index(op.f('ix_highlights_visibility_published_at'), table_name='highlights')
    op.drop_index(op.f('uq_highlights_bundle_id'), table_name='highlights', postgresql_where='((bundle_id IS NOT NULL) AND (deleted_at IS NULL))')
    op.drop_index(op.f('uq_highlights_session_id'), table_name='highlights', postgresql_where='((session_id IS NOT NULL) AND (deleted_at IS NULL))')
    op.drop_table('highlights')
    op.drop_index(op.f('ix_feed_post_comments_post_id'), table_name='feed_post_comments')
    op.drop_table('feed_post_comments')
    op.drop_index(op.f('ix_feed_posts_created_at'), table_name='feed_posts')
    op.drop_index(op.f('ix_feed_posts_expires_at'), table_name='feed_posts')
    op.drop_table('feed_posts')
    op.drop_table('profile_stats')
    op.drop_index(op.f('ix_blog_posts_profile_id_published_at'), table_name='blog_posts')
    op.drop_index(op.f('ix_blog_posts_visibility_published_at'), table_name='blog_posts')
    op.drop_index(op.f('uq_blog_posts_profile_id_slug'), table_name='blog_posts', postgresql_where='((slug IS NOT NULL) AND (deleted_at IS NULL))')
    op.drop_table('blog_posts')
    op.drop_index(op.f('ix_profiles_auth_user_id'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_created_at'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_handle'), table_name='profiles')
    op.drop_index(op.f('ix_session_bundles_profile_id_created_at'), table_name='session_bundles')
    op.drop_index(op.f('ix_session_bundles_visibility_created_at'), table_name='session_bundles')
    op.create_index(op.f('ix_session_bundles_profile_id'), 'session_bundles', ['profile_id'], unique=False)
    op.drop_index(op.f('ix_session_notes_profile_id_created_at'), table_name='session_notes')
    op.drop_index(op.f('ix_session_notes_tags_gin'), table_name='session_notes', postgresql_using='gin')
    op.create_index(op.f('ix_session_notes_profile_id'), 'session_notes', ['profile_id'], unique=False)
    op.drop_constraint(op.f('session_notes_session_id_fkey'), 'session_notes', type_='foreignkey')
    op.drop_index(op.f('ix_sessions_profile_id_started_at'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_status_created_at'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_visibility_created_at'), table_name='sessions')
    op.drop_index(op.f('uq_sessions_one_active_per_profile'), table_name='sessions', postgresql_where="((status = 'active'::session_status_enum) AND (deleted_at IS NULL))")
    op.create_index(op.f('ix_sessions_profile_id'), 'sessions', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_profile_id'), table_name='sessions')
    op.create_index(op.f('uq_sessions_one_active_per_profile'), 'sessions', ['profile_id'], unique=True, postgresql_where="((status = 'active'::session_status_enum) AND (deleted_at IS NULL))")
    op.create_index(op.f('ix_sessions_visibility_created_at'), 'sessions', ['visibility', 'created_at'], unique=False)
    op.create_index(op.f('ix_sessions_status_created_at'), 'sessions', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_sessions_profile_id_started_at'), 'sessions', ['profile_id', 'started_at'], unique=False)
    op.create_foreign_key(op.f('session_notes_session_id_fkey'), 'session_notes', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_session_notes_profile_id'), table_name='session_notes')
    op.create_index(op.f('ix_session_notes_tags_gin'), 'session_notes', ['tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_session_notes_profile_id_created_at'), 'session_notes', ['profile_id', 'created_at'], unique=False)
    op.drop_index(op.f('ix_session_bundles_profile_id'), table_name='session_bundles')
    op.create_index(op.f('ix_session_bundles_visibility_created_at'), 'session_bundles', ['visibility', 'created_at'], unique=False)
    op.create_index(op.f('ix_session_bundles_profile_id_created_at'), 'session_bundles', ['profile_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_profiles_handle'), 'profiles', ['handle'], unique=True)
    op.create_index(op.f('ix_profiles_created_at'), 'profiles', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_profiles_auth_user_id'), 'profiles', ['auth_user_id'], unique=True)
    op.create_table('blog_posts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('slug', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('excerpt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('body_md', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('cover_image_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('visibility', postgresql.ENUM('public', 'private', name='visibility_enum'), server_default=sa.text("'public'::visibility_enum"), autoincrement=False, nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('blog_posts_profile_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('blog_posts_pkey'))
    )
    op.create_index(op.f('uq_blog_posts_profile_id_slug'), 'blog_posts', ['profile_id', 'slug'], unique=True, postgresql_where='((slug IS NOT NULL) AND (deleted_at IS NULL))')
    op.create_index(op.f('ix_blog_posts_visibility_published_at'), 'blog_posts', ['visibility', 'published_at'], unique=False)
    op.create_index(op.f('ix_blog_posts_profile_id_published_at'), 'blog_posts', ['profile_id', 'published_at'], unique=False)
    op.create_table('feed_post_comments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['profiles.id'], name=op.f('feed_post_comments_author_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['feed_posts.id'], name=op.f('feed_post_comments_post_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('feed_post_comments_pkey'))
    )
    op.create_index(op.f('ix_feed_post_comments_post_id'), 'feed_post_comments', ['post_id'], unique=False)
    op.create_table('profile_stats',
    sa.Column('profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('total_sessions', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('total_focus_minutes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('total_blog_posts', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('total_highlights', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('current_streak_days', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('profile_stats_profile_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', name=op.f('profile_stats_pkey'))
    )
    op.create_table('feed_posts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['profiles.id'], name=op.f('feed_posts_author_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('feed_posts_pkey'))
    )
    op.create_index(op.f('ix_feed_posts_expires_at'), 'feed_posts', ['expires_at'], unique=False)
    op.create_index(op.f('ix_feed_posts_created_at'), 'feed_posts', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('highlights',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_type', postgresql.ENUM('session', 'session_bundle', name='highlight_source_type_enum'), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('bundle_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('caption', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rendered_image_path', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source_photo_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('template_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('visibility', postgresql.ENUM('public', 'private', name='visibility_enum'), server_default=sa.text("'public'::visibility_enum"), autoincrement=False, nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("source_type = 'session'::highlight_source_type_enum AND session_id IS NOT NULL AND bundle_id IS NULL OR source_type = 'session_bundle'::highlight_source_type_enum AND bundle_id IS NOT NULL AND session_id IS NULL", name=op.f('ck_highlights_source_consistency')),
    sa.ForeignKeyConstraint(['bundle_id'], ['session_bundles.id'], name=op.f('highlights_bundle_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('highlights_session_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('highlights_pkey'))
    )
    op.create_index(op.f('uq_highlights_session_id'), 'highlights', ['session_id'], unique=True, postgresql_where='((session_id IS NOT NULL) AND (deleted_at IS NULL))')
    op.create_index(op.f('uq_highlights_bundle_id'), 'highlights', ['bundle_id'], unique=True, postgresql_where='((bundle_id IS NOT NULL) AND (deleted_at IS NULL))')
    op.create_index(op.f('ix_highlights_visibility_published_at'), 'highlights', ['visibility', 'published_at'], unique=False)
    op.create_index(op.f('ix_highlights_profile_id_published_at'), 'highlights', ['profile_id', 'published_at'], unique=False)
    op.drop_table('logs')
    op.drop_table('interests')
    # ### end Alembic commands ###
